# np.sort 
Return a sorted copy of an array

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([45,  4, 82, 89, 71,  5, 67, 98, 34, 83, 91, 60, 31, 96, 56],
      dtype=int32)

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[75, 96, 60, 77],
       [92, 37, 18, 57],
       [53, 62, 68,  7],
       [56, 27, 22, 47],
       [48, 26, 90, 98],
       [84, 26, 71, 78]], dtype=int32)

In [4]:
np.sort(a)[::1]

array([ 4,  5, 31, 34, 45, 56, 60, 67, 71, 82, 83, 89, 91, 96, 98],
      dtype=int32)

In [5]:
np.sort(b,axis = 0)

array([[48, 26, 18,  7],
       [53, 26, 22, 47],
       [56, 27, 60, 57],
       [75, 37, 68, 77],
       [84, 62, 71, 78],
       [92, 96, 90, 98]], dtype=int32)

# np.append
the numpy.append() appends value along the mentioned axis at the end of the array

In [6]:
# code
np.append(a,200)

array([ 45,   4,  82,  89,  71,   5,  67,  98,  34,  83,  91,  60,  31,
        96,  56, 200])

In [7]:
b

array([[75, 96, 60, 77],
       [92, 37, 18, 57],
       [53, 62, 68,  7],
       [56, 27, 22, 47],
       [48, 26, 90, 98],
       [84, 26, 71, 78]], dtype=int32)

In [8]:
np.append(b,np.random.random((b.shape[0],1)),axis = 1)

array([[75.        , 96.        , 60.        , 77.        ,  0.71467247],
       [92.        , 37.        , 18.        , 57.        ,  0.8865385 ],
       [53.        , 62.        , 68.        ,  7.        ,  0.45284224],
       [56.        , 27.        , 22.        , 47.        ,  0.27291749],
       [48.        , 26.        , 90.        , 98.        ,  0.65544374],
       [84.        , 26.        , 71.        , 78.        ,  0.16301235]])

# np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

Concatenate means to link, join, or chain things together in a series or sequence.

In [10]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d), axis = 1)


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [12]:
np.concatenate((c,d), axis = 0)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# np.unique
with the help of np.unique() method,  we can get the unique values from an array given as parameter in np.unique() method

In [21]:
# code 
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [22]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.exapnd_dims
with the help of numpy.expand_dims method, we can get the expanded dimension of an array

In [24]:
# code
a.shape

(15,)

In [28]:
np.expand_dims(a, axis = 0).shape



(1, 15)

In [29]:
np.expand_dims(a, axis = 1 )

array([[45],
       [ 4],
       [82],
       [89],
       [71],
       [ 5],
       [67],
       [98],
       [34],
       [83],
       [91],
       [60],
       [31],
       [96],
       [56]], dtype=int32)

# np.where
the numpy.where() function return the indices (index position) of elements in an input array where the given condition is satisfied.

In [30]:
a

array([45,  4, 82, 89, 71,  5, 67, 98, 34, 83, 91, 60, 31, 96, 56],
      dtype=int32)

In [31]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 2,  3,  4,  6,  7,  9, 10, 11, 13, 14]),)

In [32]:
# replace all the values greater than 50 with 0
np.where(a>50,0,a)

array([45,  4,  0,  0,  0,  5,  0,  0, 34,  0,  0,  0, 31,  0,  0],
      dtype=int32)

In [33]:
np.where(a%2 == 0,0,a)

array([45,  0,  0, 89, 71,  5, 67,  0,  0, 83, 91,  0, 31,  0,  0],
      dtype=int32)

# np.argamax
the numpy.argmax() function returns indices (index position ) of the max element of the array in a particular axis.

In [34]:
# code 
a

array([45,  4, 82, 89, 71,  5, 67, 98, 34, 83, 91, 60, 31, 96, 56],
      dtype=int32)

In [35]:
np.argmax(a)

np.int64(7)

In [36]:
b


array([[75, 96, 60, 77],
       [92, 37, 18, 57],
       [53, 62, 68,  7],
       [56, 27, 22, 47],
       [48, 26, 90, 98],
       [84, 26, 71, 78]], dtype=int32)

In [37]:
np.argmax(b, axis = 0)

array([1, 0, 4, 4])

In [38]:
np.argmax(b, axis = 1)


array([1, 0, 2, 0, 3, 0])

In [40]:
# np.argmin
np.argmin(a)

np.int64(1)

# np.cumsum
- refers to the cumulative sum.
- A cumulative sum (or running total) continuously adds up the values in a sequence.
- numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [41]:
a

array([45,  4, 82, 89, 71,  5, 67, 98, 34, 83, 91, 60, 31, 96, 56],
      dtype=int32)

In [42]:
np.cumsum(a)


array([ 45,  49, 131, 220, 291, 296, 363, 461, 495, 578, 669, 729, 760,
       856, 912])

In [43]:
b

array([[75, 96, 60, 77],
       [92, 37, 18, 57],
       [53, 62, 68,  7],
       [56, 27, 22, 47],
       [48, 26, 90, 98],
       [84, 26, 71, 78]], dtype=int32)

In [44]:
np.cumsum(b , axis = 0)

array([[ 75,  96,  60,  77],
       [167, 133,  78, 134],
       [220, 195, 146, 141],
       [276, 222, 168, 188],
       [324, 248, 258, 286],
       [408, 274, 329, 364]])

In [45]:
np.cumsum(b,axis = 1)

array([[ 75, 171, 231, 308],
       [ 92, 129, 147, 204],
       [ 53, 115, 183, 190],
       [ 56,  83, 105, 152],
       [ 48,  74, 164, 262],
       [ 84, 110, 181, 259]])

In [47]:
np.cumsum(b)

array([  75,  171,  231,  308,  400,  437,  455,  512,  565,  627,  695,
        702,  758,  785,  807,  854,  902,  928, 1018, 1116, 1200, 1226,
       1297, 1375])

In [48]:
# np.cumprod - used for cumulative sum 
np.cumprod(a)

array([                  45,                  180,                14760,
                    1313640,             93268440,            466342200,
                31244927400,        3062002885200,      104108098096800,
           8640972142034400,   786328464925130400, -8160524325620830848,
        5278162937687966336,  8641552027886874624,  4311567645216636928])

In [49]:
a

array([45,  4, 82, 89, 71,  5, 67, 98, 34, 83, 91, 60, 31, 96, 56],
      dtype=int32)

# np.percentile
numpy.percentile() function is used to compute the nth percentile of the given data (array elements ) along the specified axis.


In [50]:
a

array([45,  4, 82, 89, 71,  5, 67, 98, 34, 83, 91, 60, 31, 96, 56],
      dtype=int32)

In [51]:
np.percentile(a,50)


np.float64(67.0)

In [52]:
np.median(a)


np.float64(67.0)

# np.histogram
numpy has the built - in numpy.function() which represent the frequency of data distribution in the graphical form.

In [53]:
# code 
a


array([45,  4, 82, 89, 71,  5, 67, 98, 34, 83, 91, 60, 31, 96, 56],
      dtype=int32)

In [54]:
np.histogram(a, bins = [0,50,100])

(array([ 5, 10]), array([  0,  50, 100]))

# np.corrcoef
Return pearson product - moment correlation coefficient.

In [56]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin
with the help of numpy.isin() method,we can see that one array having values are checked in different numpy array having differebt element eith different sizes.


In [57]:
# code
a

array([45,  4, 82, 89, 71,  5, 67, 98, 34, 83, 91, 60, 31, 96, 56],
      dtype=int32)

In [58]:
items =  [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]



array([60], dtype=int32)

# np.flip
the numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of array.

In [59]:
# code
a


array([45,  4, 82, 89, 71,  5, 67, 98, 34, 83, 91, 60, 31, 96, 56],
      dtype=int32)

In [60]:
np.flip(a)

array([56, 96, 31, 60, 91, 83, 34, 98, 67,  5, 71, 89, 82,  4, 45],
      dtype=int32)

In [61]:
b


array([[75, 96, 60, 77],
       [92, 37, 18, 57],
       [53, 62, 68,  7],
       [56, 27, 22, 47],
       [48, 26, 90, 98],
       [84, 26, 71, 78]], dtype=int32)

In [62]:
np.flip(b, axis = 1)

array([[77, 60, 96, 75],
       [57, 18, 37, 92],
       [ 7, 68, 62, 53],
       [47, 22, 27, 56],
       [98, 90, 26, 48],
       [78, 71, 26, 84]], dtype=int32)

# np.put
The numpy.put() function replaces specific elements of an array with the given values of p_array. Array indexed works on falttened way.

In [63]:
# code 
a


array([45,  4, 82, 89, 71,  5, 67, 98, 34, 83, 91, 60, 31, 96, 56],
      dtype=int32)

In [66]:
np.put(a,[0,1],[110,530])

# np.delete
The numpy.delete() function returns a new array with the deletion of sub-array along with the mentioned axis .


In [67]:
# code
a


array([110, 530,  82,  89,  71,   5,  67,  98,  34,  83,  91,  60,  31,
        96,  56], dtype=int32)

In [68]:
np.delete(a,[0,2,4])

array([530,  89,   5,  67,  98,  34,  83,  91,  60,  31,  96,  56],
      dtype=int32)

# Set Functions
- np.union1d

- np.intersect1d

- np.setdiff1d

- np.setxor1d

- np.in1d

In [69]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [70]:
np.intersect1d(m,n)

array([3, 4, 5])

In [71]:
np.setdiff1d(m,n)

array([1, 2])

In [73]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]


# np.clip
np.clip() function is used to clip(limit) the values in an array.

In [80]:
# code
a

array([110, 530,  82,  89,  71,   5,  67,  98,  34,  83,  91,  60,  31,
        96,  56], dtype=int32)

In [81]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 75, 71, 25, 67, 75, 34, 75, 75, 60, 31, 75, 56],
      dtype=int32)