In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Shape:", arr.shape)
print("Mean:", np.mean(arr))

Array: [1 2 3 4 5]
Shape: (5,)
Mean: 3.0


# What is Numpy?
-NumPy stands for Numerical Python. It is a Python library used to work with arrays and perform fast mathematical operations on large amounts of data.

-It is faster than normal Python lists because it processes data in bulk using optimized code internally instead of looping element by element.

-NumPy is the foundation for most data science libraries — Pandas, Scikit-learn, and even deep learning libraries are built on top of it. That's why it's the first thing learned in any ML roadmap.

# Numpy Arrays Vs Python Sequences
1. Fixed Size
NumPy arrays have a fixed size once created. If you want to change the size, a new array is created and the old one is deleted. Python lists, on the other hand, can grow or shrink dynamically.

2. Same Data Type
All elements in a NumPy array must be of the same data type (e.g., all integers or all floats). Python lists can hold mixed data types (int, string, float together).

3. Faster Operations
NumPy arrays are much faster for mathematical operations because they are processed in bulk using optimized C code internally. Python lists require a loop to do the same task, which is slower.

4. Less Memory
NumPy arrays take less memory compared to Python lists because they store data in a more compact, fixed-type format.

5. Used in ML Libraries
Most data science and ML libraries (Pandas, Scikit-learn, TensorFlow) use NumPy arrays internally because of their speed and efficiency.

In [3]:
#Creating Numpy Arrays 
#np.array
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
#2D and #3d
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
c = np.array([[[1, 2], [3,4], [5,6], [7,8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [9]:
#dtype - check datatype of array elements 
import numpy as np
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [10]:
# np.arrange - creates an array with evenly spaced values within a given range, similar to Python's range() function. It takes 
#start, stop, and step values.
import numpy as np
b = np.arange(1, 11, 2)
print(b)

[1 3 5 7 9]


In [15]:
# with reshape -changes the shape (dimensions) of an array without changing its data. The total number of elements must remain 
#the same before and after reshaping.
import numpy as np

a = np.arange(1, 11)
print("Original:", a)

b = a.reshape(5, 2)
print("Reshaped:\n", b)

Original: [ 1  2  3  4  5  6  7  8  9 10]
Reshaped:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [16]:
# np.ones and np.zeros - np.ones() creates an array filled with 1s, and np.zeros() creates an array filled with 0s. Both take the shape of the array as input. These are commonly used to initialize arrays 
#before filling them with actual data.
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
#np.random - np.random creates an array filled with random values between 0 and 1.
np.random.random((3,4))

array([[0.06623895, 0.79940993, 0.0282061 , 0.27831514],
       [0.84108499, 0.10330995, 0.06793687, 0.55905859],
       [0.09878012, 0.21124747, 0.72097424, 0.26533917]])

In [20]:
#np.linspace - np.linspace creates evenly spaced numbers between a start and end value (we specify how many numbers we want, not the step size).
np.linspace(-10, 10 , 10, dtype = int)


array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [21]:
#np.identity - np.identity creates an identity matrix  (square matrix with 1s on the diagonal and 0s elsewhere).
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
#Array Attributes 
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
%autosave 10

Autosaving every 10 seconds


In [24]:
#ndim - number of dimensions of the array
a3.ndim

3

In [25]:
# shape - size of array in each dimension (rows, columns)
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
# size - total number of elements in the array
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [27]:
#item size - memory (in bytes) taken by each element
a3.itemsize

8

In [28]:
#dtype -data type of elements stored in the array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [29]:
# Changing datatype
#astype - astype() is used to convert the data type of an existing array to another data type. It does not change the original 
#array, instead it returns a new array with the converted type.
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [3]:
# Array operations
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
#scalar operations - Scalar operations apply a single value (scalar) to every element of an array. NumPy applies the operation element-wise 
#automatically without needing a loop.
#airthmetic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [5]:
#relational - Relational operators compare each element of an array with a value (or another array) and return a boolean array as result.
a2 ==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [6]:
# vector operations - When two arrays of the same shape are operated together, the operation happens element-wise between corresponding positions.
# airthmetic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [8]:
# Array Functions
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[45.,  9.,  8.],
       [81., 68., 69.],
       [27., 25.,  5.]])

In [10]:
## max/min/sum/prod - These functions work on the entire array by default. Using axis=0 applies the function column-wise, and axis=1 applies it row-wise.
# 0 -> col and 1 -> row
np.prod(a1, axis=0)
a = np.random.random((3, 3))
a = np.round(a * 100)
print(a)

print("Max:", np.max(a))
print("Min:", np.min(a))
print("Sum:", np.sum(a))
print("Prod:", np.prod(a))

print("Max col-wise:", np.max(a, axis=0))
print("Max row-wise:", np.max(a, axis=1))

[[18. 54. 95.]
 [41. 36. 35.]
 [30. 43. 92.]]
Max: 95.0
Min: 18.0
Sum: 444.0
Prod: 566137352592000.0
Max col-wise: [41. 54. 95.]
Max row-wise: [95. 41. 92.]


In [11]:
# mean/median/std/var - 
#mean - average of elements
#median - middle value when sorted
#std - standard deviation (spread of data)
#var - variance (square of standard deviation)
print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Std:", np.std(a))
print("Var:", np.var(a))

Mean: 49.333333333333336
Median: 41.0
Std: 25.333333333333336
Var: 641.7777777777778


In [12]:
# trigonometric functions - NumPy provides built-in trigonometric functions (sin, cos, tan) that apply element-wise on the array, just like scalar operations.
# trigonometric functions
print("Sin:\n", np.sin(a))
print("Cos:\n", np.cos(a))
print("Tan:\n", np.tan(a))
np.sin(a1)

Sin:
 [[-0.75098725 -0.55878905  0.68326171]
 [-0.15862267 -0.99177885 -0.42818267]
 [-0.98803162 -0.83177474 -0.77946607]]
Cos:
 [[ 0.66031671 -0.82930983  0.73017356]
 [-0.98733928 -0.12796369 -0.90369221]
 [ 0.15425145  0.5551133  -0.62644445]]
Tan:
 [[-1.13731371  0.6738001   0.93575247]
 [ 0.1606567   7.75047091  0.47381472]
 [-6.4053312  -1.49838734  1.24427006]]


array([[ 0.85090352,  0.41211849,  0.98935825],
       [-0.62988799, -0.89792768, -0.11478481],
       [ 0.95637593, -0.13235175, -0.95892427]])

In [13]:
# dot product - Dot product is matrix multiplication between two arrays. For this, the number of columns in the first array must match the number of rows in the second array.
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
a2 = np.arange(12).reshape(3, 4)
b2 = np.arange(12, 24).reshape(4, 3)

print(np.dot(a2, b2))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [14]:
# log and exponenets - np.log() calculates the natural logarithm of each element. np.exp() calculates e (Euler's number) raised to the power of 
#each element.
np.exp(a1)
a3 = np.arange(1, 11)

print("Log:\n", np.log(a3))
print("Exp:\n", np.exp(a3))

Log:
 [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
Exp:
 [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [15]:
# round/floor/ceil- round() rounds to the nearest value. floor() always rounds down to the smaller integer. ceil() always rounds up to the 
#larger integer.
np.ceil(np.random.random((2,3))*100)
a4 = np.random.random((2, 3)) * 100
print(a4)

print("Round:\n", np.round(a4))
print("Floor:\n", np.floor(a4))
print("Ceil:\n", np.ceil(a4))

[[42.24464831 80.12298919  5.93177416]
 [36.54528136 82.8252827  37.51750975]]
Round:
 [[42. 80.  6.]
 [37. 83. 38.]]
Floor:
 [[42. 80.  5.]
 [36. 82. 37.]]
Ceil:
 [[43. 81.  6.]
 [37. 83. 38.]]


In [16]:
# indexing and slicing 
#Indexing is used to access a specific element of an array using its position. Slicing is used to access a range of elements 
#using start:stop:step format.

#For 2D and 3D arrays, indexing/slicing works separately for 
#each dimension, separated by a comma.
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
a2[1,0]

np.int64(4)

In [21]:
a3[1,0,1]

np.int64(5)

In [22]:
a3[1,1,0]


np.int64(6)

In [23]:
#1D Array
import numpy as np
a = np.arange(10)
print(a)
print("Index 5:", a[5])
print("Slice 2:5:", a[2:5])
print("Slice with step:", a[::2])
print("Reverse:", a[::-1])

[0 1 2 3 4 5 6 7 8 9]
Index 5: 5
Slice 2:5: [2 3 4]
Slice with step: [0 2 4 6 8]
Reverse: [9 8 7 6 5 4 3 2 1 0]


In [25]:
#2D Array
b = np.arange(12).reshape(3,4)
print(b)
print("element at [1,2]:", b [1,2])
print("Row 1:", b[1])
print("Column 2:", b[:, 2])
print("Slice rows 0-1, cols 1-3:\n", b[0:2, 1:3])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
element at [1,2]: 6
Row 1: [4 5 6 7]
Column 2: [ 2  6 10]
Slice rows 0-1, cols 1-3:
 [[1 2]
 [5 6]]


In [26]:
# 3D Array
c = np.arange(24).reshape(2, 3, 4)
print(c)

print("Element:", c[1, 1, 2])
print("Slice:\n", c[1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Element: 18
Slice:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [27]:
# Iterating - Iterating means going through each element of an array one by one, usually with a loop. For 1D arrays, a normal for loop 
#works directly. For multi-dimensional arrays, normal looping gives rows/sub-arrays instead of individual elements, so np.nditer() is used to iterate 
#over every single element regardless of dimensions.
#1D Array
a1 
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [28]:
#2D Array
for i in a2:
    print(i)
    

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [29]:
# iterating - element by element using nditer
#3D Array

for i in np.nditer(b):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
# Reshaping - reshape, transpose, ravel

#reshape() changes the shape of an array without changing data.
#transpose() flips rows into columns and columns into rows.
#ravel() converts a multi-dimensional array into a 1D array.

# reshape
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)

In [30]:
# transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [31]:
# ravel
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
# Stacking - horizontal and vertical

#Stacking combines two or more arrays together. np.hstack() joins arrays side by side (horizontally) — number of rows must match. 
#np.vstack() joins arrays on top of each other (vertically) — number of columns must match.
#horizontal stacking 
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(4,3)

a5


array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [37]:
# stacking
a = np.arange(12).reshape(3, 4)
b = np.arange(12, 24).reshape(3, 4)

print("Horizontal stack:\n", np.hstack((a, b)))
print("Vertical stack:\n", np.vstack((a, b)))

Horizontal stack:
 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
Vertical stack:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [42]:
# Splitting - horizontal and vertical

#Splitting breaks one array into multiple smaller arrays.
##np.hsplit() splits an array into equal column-wise parts.
#np.vsplit() splits an array into equal row-wise parts.
#The number of splits must evenly divide the array.
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)

print("Horizontal split:")
print(np.hsplit(a, 2))

print("Vertical split:")
print(np.vsplit(a, 3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Horizontal split:
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
Vertical split:
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
